# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SmartTranslator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartTranslator

  pod "ViewAnimator" # ViewAnimator for cool animations
  pod 'lottie-ios' # Lottie for Animation
  pod 'MLTranslate', '~>2.0.5.300' # Real-time translation
  pod 'MLLangDetection', '~>2.0.5.300' # Real-Time Language Detection
  
end
